spring.application.name=user-service

#database
spring.mongodb.uri=mongodb+srv://daniealantony:ACNuHiGDPLI7H9kk@user-data.c0kmgfx.mongodb.net/?appName=user-data
spring.mongodb.database=userdb

server.port=8082



