spring.application.name=Ecom-product

server.port=8081

#database
spring.datasource.url=jdbc:postgresql:@ep-blue-wind-ataaqdfl.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_lqIgM8x9VCLZ

spring.jpa.show-sql=true
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

