spring.application.name=Order


server.port=8083

#database
spring.datasource.url=jdbc:postgresql://localhost:5432/Order
spring.datasource.username=dani
spring.datasource.password=dani2005

spring.jpa.show-sql=true
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect